# Generated by Django 2.2.4 on 2020-11-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='Book',
        ),
        migrations.AddField(
            model_name='authors',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='books_authors_app.Books'),
        ),
    ]
