# Generated by Django 2.2.4 on 2020-11-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_auto_20201108_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='books_authors_app.Books'),
        ),
    ]
