# Generated by Django 2.2.4 on 2020-11-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshowsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='descrption',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
    ]
